RETURN_SOURCE_DOCUMENTS: True
VECTOR_COUNT: 3
CHUNK_SIZE: 512
CHUNK_OVERLAP: 10
DATA_PATH: 'data/'
DB_FAISS_PATH: 'vectorstore/db_faiss'
MODEL_BIN_PATH: './models/mistral/mistral-7b-instruct-v0.1.Q5_K_M.gguf'
MODEL_TYPE: 'mistral'
#MODEL_BIN_PATH: 'models/llama-2-7b-chat.ggmlv3.q8_0.bin'
MAX_NEW_TOKENS: 512 # 200 # 3000
TEMPERATURE: 0.2 #0.01 # 0.2
VERBOSE: True
THREADS: 4
INTERNET: True
PROMPT: 'qa_mistral'
GPU: True