RETURN_SOURCE_DOCUMENTS: True
VECTOR_COUNT: 3
CHUNK_SIZE: 512
CHUNK_OVERLAP: 10
DATA_PATH: 'data/'
DB_FAISS_PATH: 'vectorstore/db_faiss'
MODEL_BIN_PATH: './models/llama/llama-2-7b-chat.Q5_K_M.gguf'
MODEL_TYPE: 'llama'
MAX_NEW_TOKENS: 512 # 200 # 3000
TEMPERATURE: 0.2 #0.01 # 0.2
VERBOSE: True
THREADS: 4
INTERNET: True
PROMPT: 'qa_llama'
GPU: True